[package]

name = "mio"
version = "0.0.1"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
time = "*"

[dependencies.nix]

git = "https://github.com/vberger/nix-rust.git"
rev = "078fff6bc3a9a14ee11ec979397a193d4468ca90"

[[test]]

name = "test"
path = "test/test.rs"
